Attaching to csci143-final_web_1, csci143-final_db_1
[33mweb_1  |[0m Waiting for postgres...
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[33mweb_1  |[0m postgres: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
[36mdb_1   |[0m The files belonging to this database system will be owned by user "postgres".
[36mdb_1   |[0m This user must also own the server process.
[36mdb_1   |[0m 
[36mdb_1   |[0m The database cluster will be initialized with locale "en_US.utf8".
[36mdb_1   |[0m The default database encoding has accordingly been set to "UTF8".
[36mdb_1   |[0m The default text search configuration will be set to "english".
[36mdb_1   |[0m 
[36mdb_1   |[0m Data page checksums are disabled.
[36mdb_1   |[0m 
[36mdb_1   |[0m fixing permissions on existing directory /var/lib/postgresql/data ... ok
[36mdb_1   |[0m creating subdirectories ... ok
[36mdb_1   |[0m selecting dynamic shared memory implementation ... posix
[36mdb_1   |[0m selecting default max_connections ... 100
[36mdb_1   |[0m selecting default shared_buffers ... 128MB
[36mdb_1   |[0m selecting default time zone ... Etc/UTC
[36mdb_1   |[0m creating configuration files ... ok
[36mdb_1   |[0m running bootstrap script ... ok
[36mdb_1   |[0m performing post-bootstrap initialization ... ok
[36mdb_1   |[0m initdb: warning: enabling "trust" authentication for local connections
[36mdb_1   |[0m initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
[36mdb_1   |[0m syncing data to disk ... ok
[36mdb_1   |[0m 
[36mdb_1   |[0m 
[36mdb_1   |[0m Success. You can now start the database server using:
[36mdb_1   |[0m 
[36mdb_1   |[0m     pg_ctl -D /var/lib/postgresql/data -l logfile start
[36mdb_1   |[0m 
[36mdb_1   |[0m waiting for server to start....2024-05-06 17:33:18.295 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
[36mdb_1   |[0m 2024-05-06 17:33:18.296 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m 2024-05-06 17:33:18.301 UTC [51] LOG:  database system was shut down at 2024-05-06 17:33:18 UTC
[36mdb_1   |[0m 2024-05-06 17:33:18.308 UTC [48] LOG:  database system is ready to accept connections
[36mdb_1   |[0m  done
[36mdb_1   |[0m server started
[36mdb_1   |[0m 
[36mdb_1   |[0m /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01.sql
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m BEGIN
[36mdb_1   |[0m CREATE TABLE
[36mdb_1   |[0m CREATE TABLE
[36mdb_1   |[0m CREATE INDEX
[36mdb_1   |[0m CREATE INDEX
[36mdb_1   |[0m CREATE TABLE
[36mdb_1   |[0m 
[36mdb_1   |[0m 
[36mdb_1   |[0m /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/10_postgis.sh
[36mdb_1   |[0m CREATE DATABASE
[36mdb_1   |[0m Loading PostGIS extensions into template_postgis
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m You are now connected to database "template_postgis" as user "postgres".
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m Loading PostGIS extensions into postgres
[36mdb_1   |[0m NOTICE:  extension "postgis" already exists, skipping
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m You are now connected to database "postgres" as user "postgres".
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m CREATE EXTENSION
[36mdb_1   |[0m 
[36mdb_1   |[0m waiting for server to shut down....2024-05-06 17:33:20.939 UTC [48] LOG:  received fast shutdown request
[36mdb_1   |[0m 2024-05-06 17:33:20.940 UTC [48] LOG:  aborting any active transactions
[36mdb_1   |[0m 2024-05-06 17:33:20.943 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
[36mdb_1   |[0m 2024-05-06 17:33:20.944 UTC [49] LOG:  shutting down
[36mdb_1   |[0m 2024-05-06 17:33:20.945 UTC [49] LOG:  checkpoint starting: shutdown immediate
[36mdb_1   |[0m 2024-05-06 17:33:21.001 UTC [49] LOG:  checkpoint complete: wrote 3813 buffers (23.3%); 0 WAL file(s) added, 0 removed, 2 recycled; write=0.049 s, sync=0.006 s, total=0.057 s; sync files=794, longest=0.002 s, average=0.001 s; distance=31699 kB, estimate=31699 kB; lsn=0/33DBED0, redo lsn=0/33DBED0
[36mdb_1   |[0m 2024-05-06 17:33:21.022 UTC [48] LOG:  database system is shut down
[36mdb_1   |[0m  done
[36mdb_1   |[0m server stopped
[36mdb_1   |[0m 
[36mdb_1   |[0m PostgreSQL init process complete; ready for start up.
[36mdb_1   |[0m 
[36mdb_1   |[0m 2024-05-06 17:33:21.077 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
[36mdb_1   |[0m 2024-05-06 17:33:21.077 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[36mdb_1   |[0m 2024-05-06 17:33:21.078 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[36mdb_1   |[0m 2024-05-06 17:33:21.078 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m 2024-05-06 17:33:21.082 UTC [72] LOG:  database system was shut down at 2024-05-06 17:33:20 UTC
[36mdb_1   |[0m 2024-05-06 17:33:21.089 UTC [1] LOG:  database system is ready to accept connections
